.DEFAULT_GOAL : all

all: clean build run

clean:
	cargo clean
build:
	cargo build
run:
	cargo run <input.txt
fast:
	cargo clean;
	cargo build;
	cargo run < input.txt;
fast2:
	cargo clean;
	cargo build;
	cargo run < input2.txt;
# expected output is 61537